Repository damongolding/immich-kiosk, pull requests merged in 2025-04, with the labels that each got.

#356 test slice length for emptyness
  internal/immich/immich_helpers.go
  internal/immich/immich_test.go
Labels: fix

#355 Feature/person age
  README.md
  config.example.yaml
  frontend/public/assets/css/kiosk.css
  frontend/src/css/image.css
  internal/config/config.go
  internal/immich/immich.go
  internal/immich/immich_helpers.go
  internal/immich/immich_test.go
  internal/templates/partials/icon.templ
  internal/templates/partials/metadata.templ
  internal/templates/partials/more_info.templ
  internal/utils/utils.go
  taskfile.yml
Labels: enhancement

#360 QR scales with font
  frontend/public/assets/css/kiosk.css
  frontend/src/css/more-info.css
  internal/templates/partials/more_info.templ
Labels: fix

#359 Feature/people all
  README.md
  internal/config/config_validation.go
  internal/immich/immich.go
  internal/immich/immich_helpers.go
  internal/immich/immich_person.go
  internal/kiosk/kiosk.go
  internal/routes/routes_asset_helpers.go
  taskfile.yml
Labels: enhancement

#366 first pass at adding linear history movement
  README.md
  config.example.yaml
  frontend/public/assets/js/kiosk.js
  frontend/src/ts/kiosk.ts
  internal/cache/cache.go
  internal/kiosk/kiosk.go
  internal/routes/routes_asset.go
  internal/routes/routes_asset_helpers.go
  internal/routes/routes_previous_asset.go
  internal/routes/routes_webhooks.go
  internal/templates/components/image/image.templ
  internal/templates/components/video/video.templ
  internal/templates/partials/history.templ
  internal/webhooks/webhooks.go
  main.go
  taskfile.yml
Labels: enhancement

#369 !ShowPersonName && ShowPersonAge will only show names with ages
  internal/templates/partials/metadata.templ
Labels: enhancement

#372 add custom css class
  README.md
  internal/config/config.go
  internal/templates/partials/body.templ
Labels: enhancement

#382 Feature/demo
  .gitignore
  Dockerfile
  README.md
  demo.config.yaml
  frontend/public/assets/js/kiosk.js
  frontend/src/ts/kiosk.ts
  go.mod
  go.sum
  internal/cache/cache.go
  internal/config/config.go
  internal/config/config_validation.go
  internal/demo/demo.go
  internal/immich/immich_helpers.go
  internal/routes/routes_asset.go
  internal/routes/routes_video.go
  internal/routes/routes_webhooks.go
  internal/templates/views/views_home.templ
  internal/webhooks/webhooks.go
  main.go
  taskfile.yml
Labels: enhancement

#378 Rename pre_fetch config option to prefetch for consistency
  config.example.yaml
Labels: documentation

#387 Fix/video image
  README.md
  internal/video/video.go
Labels: fix
