Repository damongolding/immich-kiosk, pull requests merged in 2025-01, with the labels that each got.

#254 add landscape and portrait layouts
  README.md
  go.mod
  go.sum
  internal/routes/routes_image_helpers.go
Labels: enhancement

#257 Feature/disable gpu
  README.md
  assets/preview.jpeg
  config.example.yaml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/assets/css/kiosk.css
  frontend/src/css/image.css
  internal/config/config.go
  internal/routes/routes.go
  internal/routes/routes_weather.go
  internal/templates/partials/head.templ
Labels: enhancement

#258 fix clock/weather container height on older browsers
  frontend/public/assets/css/kiosk.css
  frontend/src/css/clock-weather-container.css
  frontend/src/css/globals.css
  go.mod
  go.sum
  taskfile.yml
Labels: fix

#259 add local language for image meta date
  README.md
  assets/locales.md
  docker-compose.yaml
  go.mod
  go.sum
  internal/config/config.go
  internal/routes/routes_image_helpers.go
  internal/templates/components/image/metadata.templ
  internal/utils/utils.go
  main.go
  taskfile.yml
Labels: enhancement

#262 dynamic manifest
  frontend/public/assets/manifest.json
  internal/routes/routes_manifest.go
  main.go
Labels: enhancement

#264 fix for clock when using disable_ui
  frontend/public/assets/js/kiosk.js
  frontend/src/ts/clock.ts
Labels: fix

#266 add memories asset bucket
  README.md
  config.example.yaml
  internal/config/config.go
  internal/immich/immich.go
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_memories.go
  internal/kiosk/kiosk.go
  internal/routes/routes_image_helpers.go
  internal/templates/components/image/metadata.templ
Labels: enhancement

#267 api recursion
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_faces.go
  internal/immich/immich_favourites.go
  internal/immich/immich_memories.go
  internal/immich/immich_person.go
  internal/immich/immich_random.go
Labels: fix

#270 bypass sleep mode via URL
  README.md
  internal/config/config.go
  internal/routes/routes_image.go
  internal/routes/routes_previous_image.go
  internal/templates/partials/sleep.templ
  internal/templates/views/views_home.templ
Labels: enhancement

#271 deps and go bump
  Dockerfile
  frontend/package.json
  frontend/pnpm-lock.yaml
  go.mod
Labels: maintenance

#269 redirect frontend GUI
  frontend/public/assets/css/kiosk.css
  frontend/public/assets/js/kiosk.js
  frontend/src/css/clock-weather-container.css
  frontend/src/css/image.css
  frontend/src/css/kiosk.css
  frontend/src/css/menu.css
  frontend/src/css/more-info.css
  frontend/src/css/redirects.css
  frontend/src/css/vars.css
  frontend/src/ts/kiosk.ts
  frontend/src/ts/menu.ts
  internal/templates/partials/menu.templ
  internal/templates/partials/redirects.templ
  internal/templates/views/views_home.templ
  taskfile.yml
Labels: enhancement

#272 README hyperlink typo
  README.md
Labels: documentation

#283 Feature/album and people names
  frontend/public/assets/css/kiosk.css
  frontend/src/css/image.css
  frontend/src/css/kiosk.css
  frontend/src/css/utis.css
  internal/immich/immich.go
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_memories.go
  internal/immich/immich_person.go
  internal/routes/routes_asset_helpers.go
  internal/routes/routes_previous_asset.go
  internal/templates/partials/metadata.templ
Labels: enhancement, fix

#286 album people name missing fix
  internal/immich/immich.go
  internal/immich/immich_album.go
  internal/immich/immich_faces.go
Labels: fix

#288 disable navigation
  frontend/public/assets/js/kiosk.js
  frontend/src/ts/kiosk.ts
  frontend/src/ts/menu.ts
  frontend/src/ts/polling.ts
  internal/config/config.go
  internal/templates/views/views_home.templ
Labels: enhancement
