Repository damongolding/immich-kiosk, pull requests merged in 2025-02, with the labels that each got.

#290 date: last_XX_days
  internal/immich/immich_date.go
  internal/immich/immich_test.go
  taskfile.yml
Labels: enhancement

#231 feature: support multiple users with multiple api keys
  README.md
  config.example.yaml
  internal/cache/cache.go
  internal/common/common.go
  internal/config/config.go
  internal/config/config_test.go
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_favourites.go
  internal/immich/immich_helpers.go
  internal/immich/immich_memories.go
  internal/immich/immich_person.go
  internal/immich/immich_random.go
  internal/routes/routes_image_helpers.go
  internal/routes/routes_previous_image.go
  internal/templates/components/image/history.templ
  internal/templates/components/image/metadata.templ
Labels: enhancement

#291 feature/date_filter
  README.md
  config.example.yaml
  internal/config/config.go
  internal/immich/immich_date.go
  internal/immich/immich_person.go
  taskfile.yml
Labels: enhancement

#292 deps
  Dockerfile
  frontend/package.json
  frontend/pnpm-lock.yaml
  go.mod
  go.sum
Labels: maintenance

#279 experimental album videos
  Dockerfile
  README.md
  config.example.yaml
  docker-compose.yaml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/assets/css/kiosk.css
  frontend/public/assets/js/kiosk.js
  frontend/src/css/image.css
  frontend/src/css/kiosk.css
  frontend/src/css/menu.css
  frontend/src/css/more-info.css
  frontend/src/css/progress.css
  frontend/src/css/redirects.css
  frontend/src/css/utis.css
  frontend/src/css/video.css
  frontend/src/ts/clock.ts
  frontend/src/ts/frames.ts
  frontend/src/ts/kiosk.ts
  frontend/src/ts/locales.ts
  frontend/src/ts/menu.ts
  frontend/src/ts/polling.ts
  go.mod
  go.sum
  internal/cache/cache.go
  internal/common/common.go
  internal/config/config.go
  internal/immich/immich.go
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_faces.go
  internal/immich/immich_favourites.go
  internal/immich/immich_helpers.go
  internal/immich/immich_memories.go
  internal/immich/immich_person.go
  internal/immich/immich_test.go
  internal/immich/immich_video.go
  internal/routes/routes.go
  internal/routes/routes_asset.go
  internal/routes/routes_asset_helpers.go
  internal/routes/routes_previous_asset.go
  internal/routes/routes_test.go
  internal/routes/routes_video.go
  internal/routes/routes_webhooks.go
  internal/templates/components/image/history.templ
  internal/templates/components/image/image.templ
  internal/templates/components/image/layout.templ
  internal/templates/components/image/metadata.templ
  internal/templates/components/video/video.templ
  internal/templates/partials/history.templ
  internal/templates/partials/menu.templ
  internal/templates/partials/metadata.templ
  internal/templates/partials/more_info.templ
  internal/templates/views/views_home.templ
  internal/utils/utils.go
  internal/video/video.go
  internal/webhooks/webhooks.go
  main.go
  taskfile.yml
Labels: enhancement

#299 Feature/blacklist
  README.md
  frontend/public/assets/js/kiosk.js
  internal/config/config.go
  internal/immich/immich.go
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_favourites.go
  internal/immich/immich_helpers.go
  internal/immich/immich_memories.go
  internal/immich/immich_person.go
  internal/immich/immich_random.go
  internal/kiosk/kiosk.go
Labels: enhancement

#300 Feature/relative splitview images
  frontend/public/assets/css/kiosk.css
  frontend/src/css/image.css
  internal/common/common.go
  internal/config/config.go
  internal/immich/immich.go
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_faces.go
  internal/immich/immich_favourites.go
  internal/immich/immich_helpers.go
  internal/immich/immich_memories.go
  internal/immich/immich_person.go
  internal/immich/immich_random.go
  internal/kiosk/kiosk.go
  internal/routes/routes.go
  internal/routes/routes_asset_helpers.go
  internal/templates/partials/metadata.templ
  taskfile.yml
Labels: enhancement

#304 Go bump and pnpm deps
  Dockerfile
  frontend/package.json
  frontend/pnpm-lock.yaml
  go.mod
  go.sum
Labels: maintenance

#307 more info overlay date and location
  internal/templates/partials/metadata.templ
  internal/templates/partials/more_info.templ
Labels: fix

#309 date titlecase
  frontend/public/assets/css/kiosk.css
  frontend/src/css/clock.css
  internal/templates/partials/metadata.templ
  taskfile.yml
Labels: fix

#318 fix for today_to_today
  README.md
  internal/config/config.go
  internal/config/config_validation.go
  internal/immich/immich_album.go
  internal/immich/immich_date.go
  internal/immich/immich_favourites.go
  internal/immich/immich_helpers.go
  internal/immich/immich_memories.go
  internal/immich/immich_person.go
  internal/immich/immich_random.go
  internal/immich/immich_tag.go
  internal/routes/routes_asset_helpers.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  internal/video/video.go
  internal/weather/weather.go
Labels: fix

#324 Chore/new memory endpoint
  README.md
  frontend/public/assets/css/kiosk.css
  frontend/src/css/image.css
  internal/immich/immich.go
  internal/immich/immich_memories.go
  internal/routes/routes_asset_helpers.go
Labels: maintenance

#326 v0.18.0
  README.md
  frontend/public/assets/css/kiosk.css
  frontend/src/css/image.css
  internal/cache/cache.go
  internal/config/config_validation.go
  internal/immich/immich.go
  internal/immich/immich_date.go
  internal/immich/immich_memories.go
  internal/routes/routes_asset_helpers.go
  taskfile.yml
Labels: breaking-change
